services:
  frontend:
    image: ghcr.io/pashus/card-mini-games-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/pashus/card-mini-games-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - backend_uploads:/app/uploads

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 30 backend frontend

volumes:
  postgres_data:
  backend_uploads:
